language: java
jdk:
    - openjdk7
    - oraclejdk7

env: WILDFLY="8.0.0.Beta1"
env: JBOSS_HOME=$WILDFLY

before_script:
    - export ROOT_DIR=`pwd`
    - cd $HOME
    - wget http://download.jboss.org/wildfly/$WILDFLY/wildfly-$WILDFLY.tar.gz
    - tar xvfz wildfly-$WILDFLY.tar.gz
    - cd $ROOT_DIR

script: "mvn clean verify -Pwildfly-it"

install: /bin/true
notifications:
  irc:
    channels:
      - "irc.freenode.org#carcv"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"