language: java
jdk:
    - openjdk7
    - oraclejdk7

env:
    - WILDFLY="wildfly-8.0.0.Beta1"
    - JBOSS_HOME=$HOME/$WILDFLY

before_script:
    - cd $HOME
    - wget http://download.jboss.org/wildfly/$WILDFLY/$WILDFLY.tar.gz
    - tar xvfz $WILDFLY.tar.gz

script: "mvn clean verify -Pwildfly-it"

install: /bin/true
notifications:
  irc:
    channels:
      - "irc.freenode.org#carcv"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"